env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
  no-tabs: 0
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  brace-style: 
    - error
    - stroustrup
  no-unused-vars: # doesnt work
    - 2
    - args: none
  func-names:
    - error
    - never
  consistent-return: 
    - error
    - treatUndefinedAsUnspecified: true
  eqeqeq:
    - error
    - smart
  max-len: 
    - error
    - code: 200
  camelcase: off
  no-underscore-dangle: off
  