branch-defaults:
  main:
    environment: Simplepos-be-env
    group_suffix: null
environment-defaults:
  Simplepos-be-env:
    branch: main
    repository: simplepos-be
global:
  application_name: simplepos-be
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: pwuahaha
  repository: null
  sc: git
  workspace_type: Application
